###################################################################

# Created by write_sdc on Fri Dec  5 05:16:50 2025

###################################################################
set sdc_version 2.1

set_units -time ps -resistance kOhm -capacitance fF -voltage V -current uA
set_max_area 0
create_clock [get_ports clock]  -period 2000  -waveform {0 1000}
set_clock_uncertainty -setup 100  [get_clocks clock]
set_input_delay -clock clock  280  [get_ports clock]
set_input_delay -clock clock  280  [get_ports reset]
set_input_delay -clock clock  280  [get_ports {si[31]}]
set_input_delay -clock clock  280  [get_ports {si[30]}]
set_input_delay -clock clock  280  [get_ports {si[29]}]
set_input_delay -clock clock  280  [get_ports {si[28]}]
set_input_delay -clock clock  280  [get_ports {si[27]}]
set_input_delay -clock clock  280  [get_ports {si[26]}]
set_input_delay -clock clock  280  [get_ports {si[25]}]
set_input_delay -clock clock  280  [get_ports {si[24]}]
set_input_delay -clock clock  280  [get_ports {si[23]}]
set_input_delay -clock clock  280  [get_ports {si[22]}]
set_input_delay -clock clock  280  [get_ports {si[21]}]
set_input_delay -clock clock  280  [get_ports {si[20]}]
set_input_delay -clock clock  280  [get_ports {si[19]}]
set_input_delay -clock clock  280  [get_ports {si[18]}]
set_input_delay -clock clock  280  [get_ports {si[17]}]
set_input_delay -clock clock  280  [get_ports {si[16]}]
set_input_delay -clock clock  280  [get_ports {si[15]}]
set_input_delay -clock clock  280  [get_ports {si[14]}]
set_input_delay -clock clock  280  [get_ports {si[13]}]
set_input_delay -clock clock  280  [get_ports {si[12]}]
set_input_delay -clock clock  280  [get_ports {si[11]}]
set_input_delay -clock clock  280  [get_ports {si[10]}]
set_input_delay -clock clock  280  [get_ports {si[9]}]
set_input_delay -clock clock  280  [get_ports {si[8]}]
set_input_delay -clock clock  280  [get_ports {si[7]}]
set_input_delay -clock clock  280  [get_ports {si[6]}]
set_input_delay -clock clock  280  [get_ports {si[5]}]
set_input_delay -clock clock  280  [get_ports {si[4]}]
set_input_delay -clock clock  280  [get_ports {si[3]}]
set_input_delay -clock clock  280  [get_ports {si[2]}]
set_input_delay -clock clock  280  [get_ports {si[1]}]
set_input_delay -clock clock  280  [get_ports {si[0]}]
set_output_delay -clock clock  280  [get_ports {so[19]}]
set_output_delay -clock clock  280  [get_ports {so[18]}]
set_output_delay -clock clock  280  [get_ports {so[17]}]
set_output_delay -clock clock  280  [get_ports {so[16]}]
set_output_delay -clock clock  280  [get_ports {so[15]}]
set_output_delay -clock clock  280  [get_ports {so[14]}]
set_output_delay -clock clock  280  [get_ports {so[13]}]
set_output_delay -clock clock  280  [get_ports {so[12]}]
set_output_delay -clock clock  280  [get_ports {so[11]}]
set_output_delay -clock clock  280  [get_ports {so[10]}]
set_output_delay -clock clock  280  [get_ports {so[9]}]
set_output_delay -clock clock  280  [get_ports {so[8]}]
set_output_delay -clock clock  280  [get_ports {so[7]}]
set_output_delay -clock clock  280  [get_ports {so[6]}]
set_output_delay -clock clock  280  [get_ports {so[5]}]
set_output_delay -clock clock  280  [get_ports {so[4]}]
set_output_delay -clock clock  280  [get_ports {so[3]}]
set_output_delay -clock clock  280  [get_ports {so[2]}]
set_output_delay -clock clock  280  [get_ports {so[1]}]
set_output_delay -clock clock  280  [get_ports {so[0]}]
set_output_delay -clock clock  280  [get_ports rd]
set_output_delay -clock clock  280  [get_ports wr]
