###################################################################

# Created by write_sdc on Sun Dec 21 13:30:49 2025

###################################################################
set sdc_version 2.1

set_units -time ps -resistance kOhm -capacitance fF -voltage V -current uA
set_max_area 0
set_disable_timing [get_cells modified_inst_csb_inst_475_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_475_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_627_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_627_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_896_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_896_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_18_my_FIR_filter_firBlock_right_Y_reg_16__csb_out_mux]  \
-from I0 -to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_18_my_FIR_filter_firBlock_right_Y_reg_16__csb_in_mux]   \
-from I0 -to Z
set_disable_timing [get_cells modified_inst_csb_inst_505_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_505_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_19_csb_out_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_19_csb_in_mux] -from I1   \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_552_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_552_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_535_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_535_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_198_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_198_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_790_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_790_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_571_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_571_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_580_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_580_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_85_my_FIR_filter_firBlock_right_Y_reg_23__csb_out_mux]  \
-from I0 -to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_85_my_FIR_filter_firBlock_right_Y_reg_23__csb_in_mux]   \
-from I0 -to Z
set_disable_timing [get_cells modified_inst_csb_inst_113_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_113_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_52_csb_out_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_52_csb_in_mux] -from I1   \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_524_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_524_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_259_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_259_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_84_my_FIR_filter_firBlock_right_Y_reg_1__csb_out_mux]   \
-from I0 -to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_84_my_FIR_filter_firBlock_right_Y_reg_1__csb_in_mux]    \
-from I1 -to Z
set_disable_timing [get_cells modified_inst_csb_inst_313_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_313_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_862_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_862_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_695_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_695_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_162_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_162_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_184_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_184_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_842_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_842_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_36_my_FIR_filter_firBlock_right_Y_reg_21__csb_out_mux]  \
-from I0 -to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_36_my_FIR_filter_firBlock_right_Y_reg_21__csb_in_mux]   \
-from I0 -to Z
set_disable_timing [get_cells modified_inst_csb_inst_200_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_200_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_95_csb_out_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_95_csb_in_mux] -from I1   \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_96_csb_out_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_96_csb_in_mux] -from I1   \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_13_csb_out_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_13_csb_in_mux] -from I1   \
-to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_11_my_FIR_filter_firBlock_right_Y_reg_14__csb_out_mux]  \
-from I0 -to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_11_my_FIR_filter_firBlock_right_Y_reg_14__csb_in_mux]   \
-from I1 -to Z
set_disable_timing [get_cells modified_inst_csb_inst_227_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_227_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_69_my_FIR_filter_firBlock_right_Y_reg_27__csb_out_mux]  \
-from I0 -to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_69_my_FIR_filter_firBlock_right_Y_reg_27__csb_in_mux]   \
-from I0 -to Z
set_disable_timing [get_cells modified_inst_csb_inst_876_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_876_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_257_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_257_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_167_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_167_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_514_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_514_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_33_csb_out_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_33_csb_in_mux] -from I1   \
-to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_75_my_FIR_filter_firBlock_right_Y_reg_24__csb_out_mux]  \
-from I0 -to Z
set_disable_timing [get_cells                                                  \
modified_inst_csb_inst_75_my_FIR_filter_firBlock_right_Y_reg_24__csb_in_mux]   \
-from I1 -to Z
set_disable_timing [get_cells modified_inst_csb_inst_28_csb_out_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_28_csb_in_mux] -from I1   \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_434_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_434_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_355_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_355_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_585_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_585_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_768_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_768_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_65_csb_out_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_65_csb_in_mux] -from I1   \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_513_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_513_csb_in_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_39_csb_out_mux] -from I1  \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_39_csb_in_mux] -from I1   \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_897_csb_out_mux] -from I1 \
-to Z
set_disable_timing [get_cells modified_inst_csb_inst_897_csb_in_mux] -from I1  \
-to Z
create_clock [get_ports clk]  -period 2000  -waveform {0 1000}
set_clock_uncertainty -setup 100  [get_clocks clk]
set_input_delay -clock clk  280  [get_ports clk]
set_input_delay -clock clk  280  [get_ports freeze]
set_input_delay -clock clk  280  [get_ports {cfg_bits[810]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[809]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[808]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[807]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[806]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[805]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[804]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[803]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[802]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[801]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[800]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[799]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[798]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[797]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[796]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[795]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[794]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[793]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[792]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[791]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[790]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[789]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[788]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[787]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[786]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[785]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[784]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[783]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[782]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[781]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[780]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[779]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[778]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[777]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[776]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[775]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[774]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[773]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[772]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[771]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[770]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[769]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[768]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[767]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[766]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[765]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[764]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[763]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[762]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[761]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[760]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[759]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[758]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[757]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[756]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[755]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[754]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[753]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[752]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[751]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[750]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[749]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[748]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[747]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[746]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[745]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[744]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[743]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[742]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[741]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[740]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[739]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[738]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[737]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[736]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[735]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[734]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[733]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[732]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[731]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[730]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[729]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[728]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[727]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[726]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[725]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[724]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[723]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[722]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[721]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[720]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[719]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[718]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[717]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[716]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[715]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[714]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[713]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[712]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[711]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[710]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[709]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[708]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[707]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[706]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[705]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[704]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[703]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[702]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[701]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[700]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[699]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[698]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[697]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[696]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[695]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[694]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[693]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[692]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[691]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[690]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[689]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[688]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[687]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[686]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[685]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[684]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[683]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[682]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[681]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[680]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[679]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[678]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[677]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[676]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[675]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[674]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[673]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[672]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[671]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[670]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[669]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[668]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[667]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[666]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[665]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[664]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[663]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[662]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[661]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[660]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[659]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[658]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[657]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[656]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[655]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[654]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[653]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[652]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[651]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[650]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[649]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[648]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[647]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[646]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[645]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[644]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[643]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[642]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[641]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[640]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[639]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[638]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[637]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[636]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[635]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[634]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[633]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[632]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[631]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[630]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[629]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[628]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[627]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[626]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[625]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[624]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[623]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[622]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[621]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[620]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[619]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[618]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[617]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[616]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[615]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[614]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[613]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[612]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[611]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[610]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[609]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[608]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[607]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[606]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[605]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[604]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[603]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[602]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[601]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[600]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[599]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[598]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[597]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[596]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[595]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[594]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[593]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[592]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[591]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[590]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[589]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[588]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[587]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[586]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[585]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[584]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[583]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[582]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[581]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[580]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[579]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[578]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[577]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[576]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[575]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[574]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[573]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[572]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[571]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[570]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[569]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[568]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[567]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[566]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[565]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[564]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[563]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[562]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[561]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[560]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[559]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[558]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[557]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[556]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[555]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[554]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[553]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[552]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[551]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[550]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[549]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[548]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[547]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[546]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[545]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[544]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[543]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[542]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[541]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[540]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[539]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[538]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[537]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[536]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[535]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[534]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[533]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[532]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[531]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[530]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[529]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[528]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[527]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[526]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[525]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[524]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[523]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[522]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[521]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[520]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[519]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[518]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[517]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[516]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[515]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[514]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[513]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[512]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[511]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[510]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[509]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[508]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[507]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[506]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[505]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[504]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[503]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[502]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[501]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[500]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[499]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[498]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[497]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[496]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[495]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[494]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[493]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[492]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[491]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[490]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[489]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[488]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[487]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[486]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[485]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[484]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[483]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[482]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[481]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[480]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[479]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[478]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[477]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[476]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[475]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[474]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[473]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[472]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[471]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[470]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[469]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[468]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[467]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[466]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[465]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[464]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[463]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[462]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[461]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[460]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[459]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[458]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[457]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[456]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[455]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[454]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[453]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[452]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[451]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[450]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[449]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[448]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[447]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[446]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[445]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[444]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[443]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[442]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[441]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[440]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[439]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[438]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[437]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[436]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[435]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[434]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[433]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[432]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[431]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[430]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[429]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[428]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[427]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[426]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[425]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[424]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[423]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[422]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[421]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[420]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[419]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[418]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[417]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[416]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[415]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[414]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[413]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[412]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[411]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[410]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[409]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[408]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[407]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[406]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[405]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[404]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[403]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[402]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[401]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[400]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[399]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[398]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[397]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[396]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[395]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[394]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[393]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[392]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[391]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[390]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[389]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[388]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[387]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[386]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[385]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[384]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[383]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[382]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[381]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[380]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[379]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[378]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[377]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[376]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[375]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[374]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[373]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[372]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[371]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[370]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[369]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[368]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[367]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[366]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[365]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[364]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[363]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[362]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[361]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[360]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[359]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[358]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[357]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[356]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[355]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[354]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[353]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[352]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[351]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[350]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[349]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[348]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[347]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[346]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[345]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[344]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[343]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[342]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[341]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[340]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[339]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[338]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[337]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[336]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[335]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[334]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[333]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[332]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[331]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[330]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[329]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[328]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[327]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[326]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[325]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[324]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[323]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[322]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[321]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[320]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[319]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[318]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[317]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[316]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[315]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[314]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[313]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[312]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[311]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[310]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[309]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[308]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[307]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[306]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[305]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[304]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[303]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[302]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[301]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[300]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[299]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[298]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[297]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[296]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[295]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[294]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[293]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[292]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[291]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[290]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[289]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[288]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[287]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[286]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[285]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[284]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[283]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[282]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[281]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[280]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[279]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[278]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[277]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[276]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[275]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[274]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[273]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[272]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[271]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[270]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[269]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[268]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[267]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[266]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[265]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[264]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[263]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[262]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[261]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[260]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[259]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[258]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[257]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[256]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[255]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[254]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[253]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[252]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[251]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[250]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[249]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[248]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[247]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[246]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[245]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[244]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[243]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[242]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[241]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[240]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[239]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[238]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[237]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[236]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[235]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[234]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[233]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[232]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[231]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[230]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[229]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[228]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[227]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[226]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[225]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[224]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[223]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[222]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[221]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[220]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[219]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[218]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[217]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[216]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[215]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[214]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[213]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[212]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[211]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[210]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[209]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[208]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[207]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[206]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[205]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[204]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[203]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[202]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[201]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[200]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[199]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[198]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[197]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[196]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[195]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[194]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[193]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[192]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[191]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[190]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[189]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[188]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[187]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[186]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[185]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[184]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[183]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[182]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[181]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[180]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[179]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[178]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[177]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[176]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[175]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[174]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[173]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[172]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[171]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[170]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[169]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[168]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[167]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[166]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[165]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[164]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[163]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[162]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[161]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[160]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[159]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[158]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[157]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[156]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[155]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[154]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[153]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[152]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[151]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[150]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[149]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[148]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[147]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[146]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[145]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[144]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[143]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[142]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[141]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[140]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[139]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[138]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[137]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[136]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[135]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[134]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[133]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[132]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[131]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[130]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[129]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[128]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[127]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[126]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[125]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[124]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[123]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[122]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[121]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[120]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[119]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[118]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[117]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[116]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[115]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[114]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[113]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[112]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[111]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[110]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[109]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[108]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[107]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[106]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[105]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[104]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[103]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[102]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[101]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[100]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[99]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[98]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[97]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[96]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[95]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[94]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[93]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[92]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[91]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[90]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[89]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[88]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[87]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[86]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[85]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[84]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[83]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[82]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[81]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[80]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[79]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[78]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[77]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[76]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[75]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[74]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[73]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[72]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[71]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[70]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[69]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[68]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[67]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[66]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[65]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[64]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[63]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[62]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[61]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[60]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[59]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[58]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[57]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[56]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[55]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[54]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[53]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[52]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[51]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[50]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[49]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[48]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[47]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[46]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[45]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[44]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[43]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[42]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[41]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[40]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[39]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[38]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[37]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[36]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[35]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[34]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[33]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[32]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[31]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[30]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[29]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[28]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[27]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[26]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[25]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[24]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[23]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[22]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[21]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[20]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[19]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[18]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[17]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[16]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[15]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[14]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[13]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[12]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[11]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[10]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[9]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[8]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[7]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[6]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[5]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[4]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[3]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[2]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[1]}]
set_input_delay -clock clk  280  [get_ports {cfg_bits[0]}]
set_input_delay -clock clk  280  [get_ports {inData[31]}]
set_input_delay -clock clk  280  [get_ports {inData[30]}]
set_input_delay -clock clk  280  [get_ports {inData[29]}]
set_input_delay -clock clk  280  [get_ports {inData[28]}]
set_input_delay -clock clk  280  [get_ports {inData[27]}]
set_input_delay -clock clk  280  [get_ports {inData[26]}]
set_input_delay -clock clk  280  [get_ports {inData[25]}]
set_input_delay -clock clk  280  [get_ports {inData[24]}]
set_input_delay -clock clk  280  [get_ports {inData[23]}]
set_input_delay -clock clk  280  [get_ports {inData[22]}]
set_input_delay -clock clk  280  [get_ports {inData[21]}]
set_input_delay -clock clk  280  [get_ports {inData[20]}]
set_input_delay -clock clk  280  [get_ports {inData[19]}]
set_input_delay -clock clk  280  [get_ports {inData[18]}]
set_input_delay -clock clk  280  [get_ports {inData[17]}]
set_input_delay -clock clk  280  [get_ports {inData[16]}]
set_input_delay -clock clk  280  [get_ports {inData[15]}]
set_input_delay -clock clk  280  [get_ports {inData[14]}]
set_input_delay -clock clk  280  [get_ports {inData[13]}]
set_input_delay -clock clk  280  [get_ports {inData[12]}]
set_input_delay -clock clk  280  [get_ports {inData[11]}]
set_input_delay -clock clk  280  [get_ports {inData[10]}]
set_input_delay -clock clk  280  [get_ports {inData[9]}]
set_input_delay -clock clk  280  [get_ports {inData[8]}]
set_input_delay -clock clk  280  [get_ports {inData[7]}]
set_input_delay -clock clk  280  [get_ports {inData[6]}]
set_input_delay -clock clk  280  [get_ports {inData[5]}]
set_input_delay -clock clk  280  [get_ports {inData[4]}]
set_input_delay -clock clk  280  [get_ports {inData[3]}]
set_input_delay -clock clk  280  [get_ports {inData[2]}]
set_input_delay -clock clk  280  [get_ports {inData[1]}]
set_input_delay -clock clk  280  [get_ports {inData[0]}]
set_input_delay -clock clk  280  [get_ports reset]
set_output_delay -clock clk  280  [get_ports {outData[31]}]
set_output_delay -clock clk  280  [get_ports {outData[30]}]
set_output_delay -clock clk  280  [get_ports {outData[29]}]
set_output_delay -clock clk  280  [get_ports {outData[28]}]
set_output_delay -clock clk  280  [get_ports {outData[27]}]
set_output_delay -clock clk  280  [get_ports {outData[26]}]
set_output_delay -clock clk  280  [get_ports {outData[25]}]
set_output_delay -clock clk  280  [get_ports {outData[24]}]
set_output_delay -clock clk  280  [get_ports {outData[23]}]
set_output_delay -clock clk  280  [get_ports {outData[22]}]
set_output_delay -clock clk  280  [get_ports {outData[21]}]
set_output_delay -clock clk  280  [get_ports {outData[20]}]
set_output_delay -clock clk  280  [get_ports {outData[19]}]
set_output_delay -clock clk  280  [get_ports {outData[18]}]
set_output_delay -clock clk  280  [get_ports {outData[17]}]
set_output_delay -clock clk  280  [get_ports {outData[16]}]
set_output_delay -clock clk  280  [get_ports {outData[15]}]
set_output_delay -clock clk  280  [get_ports {outData[14]}]
set_output_delay -clock clk  280  [get_ports {outData[13]}]
set_output_delay -clock clk  280  [get_ports {outData[12]}]
set_output_delay -clock clk  280  [get_ports {outData[11]}]
set_output_delay -clock clk  280  [get_ports {outData[10]}]
set_output_delay -clock clk  280  [get_ports {outData[9]}]
set_output_delay -clock clk  280  [get_ports {outData[8]}]
set_output_delay -clock clk  280  [get_ports {outData[7]}]
set_output_delay -clock clk  280  [get_ports {outData[6]}]
set_output_delay -clock clk  280  [get_ports {outData[5]}]
set_output_delay -clock clk  280  [get_ports {outData[4]}]
set_output_delay -clock clk  280  [get_ports {outData[3]}]
set_output_delay -clock clk  280  [get_ports {outData[2]}]
set_output_delay -clock clk  280  [get_ports {outData[1]}]
set_output_delay -clock clk  280  [get_ports {outData[0]}]
